### ISSUE TITLE
Tagging this project with Crystal

### ISSUE THREAD

**Issue by sdogruyol** [arcage/crystal-email#16]
Hey @arcage 

Thanks a lot for this shard. Can you please tag this repo with `crystal`, `email`? It'd be easier for people searching Github.

**Comment by arcage** [comment]
Thanks for your advice.

But, I don't know how to add tags to repo.

Could you please tell me what should i do?

**Comment by sdogruyol** [comment]
When you click manage topic in the top where your project description is you should see something like below

![screen shot 2017-07-12 at 12 06 37](https://user-images.githubusercontent.com/990485/28110303-a23a4610-66fa-11e7-803f-5e1a307f149c.png)

Please add `crystal`, `email`, `smtp`

**Comment by arcage** [comment]
Thanks!!

I have done.
