### ISSUE TITLE
Release a version for shards

### ISSUE THREAD

**Issue by sdogruyol** [arcage/crystal-email#17]
Currently this shard has no tagged versions that why when you try to install with `shards` you get an error like below

```
➜  crystal-email-sample git:(master) ✗ shards
Updating https://github.com/arcage/crystal-email.git
git command failed: git ls-tree -r --full-tree --name-only v0.1.6 -- shard.yml (). Maybe a commit, branch or file doesn't exist?
```

Please release a version 🙏

**Comment by arcage** [comment]
Sorry, I missed "v" for version tags.

I think I have made  v0.1.6 release.

Could you check it?

**Comment by sdogruyol** [comment]
It works! Thank you @arcage 👍
