### ISSUE TITLE
Sending html email caused exception "Messsage has no contents"

### ISSUE THREAD

**Issue by lubanrb** [arcage/crystal-email#24]
Hi, 

When I tried to send html email, I got exception "Message has no contents". According to README, when sending email, required at least one `message`, `message_html` or `attach`. So, I guess I don't need to provide text message when I send html email. However, when I checked the code, I found in crystal-email/src/email/message.cr

raise Error::MessageError.new("Message has no contents.") if @body.empty? && @attachments.empty?

So, the logic here seems to me that text message is must even html email is being sent. (html content is written in @body_html). 

Should this be changed to something like the following?

raise Error::MessageError.new("Message has no contents.") if @body.empty? && @body_html.empty? && @attachments.empty?

Or do I misunderstand anything here? 

Thank you very much!

**Comment by arcage** [comment]
@lubanrb 
Thank you for pointing it out.

You are totally right.
I missed to include @body_html when checking whether the email has contents.

I released v0.2.1 to correct that.

Please check it.

**Comment by lubanrb** [comment]
works like a charm. thanks for the quick fix! :)
