### ISSUE TITLE
Use Logger interface instead of IO for logging

### ISSUE THREAD

**Issue by robacarp** [arcage/crystal-email#30]
First off, nice shard. I was able to get up and running quickly without issue.

While integrating this with another project, I tried to pass a [Logger](https://crystal-lang.org/api/0.24.1/Logger.html) object in to gather the logs up with the logs from the rest of the application. Is it possible to support an external logger instance?

Thanks

**Comment by arcage** [comment]
Thank you for your valuable comment.

As you said, the external logger support seem to be better than current implement.
I will consider about it.

**Comment by arcage** [comment]
I released v0.2.4 that supports external Logger instance.

**Comment by robacarp** [comment]
@arcage wow, this looks like it will do exactly what I need. Thank you for the quick patch!
