### ISSUE TITLE
Raise exception more gracefully when a fatal sending error occurs

### ISSUE THREAD

**Issue by robacarp** [arcage/crystal-email#32]
While working with https://github.com/amberframework/quartz-mailer/pull/11, integrating this shard as a mailer for Amber, I wrote this snippet:

```crystal
class Quartz::Mailer
  def self.deliver(message : Message)
    config = Quartz.config

    EMail::Sender.new(
      config.smtp_address, config.smtp_port,
      use_tls: config.use_ssl,
      logger: config.logger
    ).start do
      enqueue message.to_email
    end

  rescue e : EMail::Error::MessageError
    # this never executes because of the exit(1)
    puts "Email message couldn't be delivered."
    puts e.message
  end
end
```

However, this code has caused me some problems:

```crystal
  def start
    # ...
  rescue ex : Error
    close_socket
    fatal_error(ex)
  end

  # ...

  private def fatal_error(error : Exception)
    logging_message = error.message.try(&.gsub(/\s+/, ' ')).to_s + "(#{error.class})"
    log_fatal(logging_message)
    exit(1)
  end
```

If for some reason an email fails to send, taking down the webserver or worker process isn't a safe option for Amber.

Are you open to changing the code to something like this?

```crystal
  def start
    # ...
  rescue ex : Error
    fatal_error(ex)
  ensure
    close_socket
  end

  # ...

  private def fatal_error(error : Exception)
    logging_message = error.message.try(&.gsub(/\s+/, ' ')).to_s + "(#{error.class})"
    log_fatal(logging_message)
  end
```

I believe this would allow exceptions to be propagated up the stack as well as ensure that the client closes the connection.

If you have a suggestion of a better way to implement this, I'm open to suggestions.

Thanks

**Comment by arcage** [comment]
Thank you for pointing it.

I had completely missed the point of view that this shard is used as a part of other project.

I will correct this in this weekend.

**Comment by robacarp** [comment]
@arcage Thank you! If you'd rather not, I'm happy to put a little more work in and divide out the functionality we need into a separate gem.

**Comment by arcage** [comment]
At first, I tried the following code:

```crystal
  def start
    # ...
  rescue ex : Error
    fatal_error(ex)
  ensure
    close_socket
  end

  # ...

  private def fatal_error(error : Exception)
    logging_message = error.message.try(&.gsub(/\s+/, ' ')).to_s + "(#{error.class})"
    log_fatal(logging_message)
  end
```

This will absorb the fact that an Exception was raised.
Probably, the `rescue` block in `Quartz::Mailer.deliver` method cannot catch the error. 

Next, I tried that  `ex` is re-raised  in the `rescue` block in `Client.start`.
But, This will cause `Unhandled exception in spawn:` when the `ex` was not rescued outside of `Client.start`.
And, the program doesn't finish until the process is forcibly terminated. 

```
2018/01/27 21:46:16 [crystal-email/36884] INFO [EMail_Client] Start TCP session to smtp_server:587
2018/01/27 21:46:16 [crystal-email/36884] INFO [EMail_Client] Start TLS session
2018/01/27 21:46:16 [crystal-email/36884] INFO [EMail_Client] Authentication success with user_id / ********
2018/01/27 21:46:16 [crystal-email/36884] FATAL [EMail_Client] Message has no From address.(EMail::Error::MessageError)
2018/01/27 21:46:16 [crystal-email/36884] INFO [EMail_Client] Close session to smtp_server:587
Unhandled exception in spawn:
Message has no From address. (EMail::Error::MessageError)
  from src/email/message.cr:25:5 in 'validate!'
  from src/email/client.cr:100:5 in 'mail_validate!'
  from src/email/client.cr:105:5 in 'send'
  from ~procProc(Nil)@src/email/sender.cr:79
  from /usr/local/Cellar/crystal-lang/0.24.1_1/src/fiber.cr:255:3 in 'run'
  from ~proc2Proc(Fiber, (IO::FileDescriptor | Nil))@/usr/local/Cellar/crystal-lang/0.24.1_1/src/fiber.cr:29

```

To avoid this hung up, I think the `exit()` is necessary to finish the program. 

At last, I have considered to introduce new nilable error handler `@on_fatal_error : (Exception ->) | Nil` in `EMail::Client` class.
The default behavior (when the `@on_fatal_error` is `nil`) is that forcibly finishing the program with `exit(1)`.
Otherwise, `@on_fatal_error` will be called with `ex`.

```crystal
  def start
    # ...
  rescue ex : Error
    fatal_error(ex)
  ensure
    close_socket
  end

  def fatal_error(ex : Exception)
    log_fatal(ex.message.try(&.gsub(/\s+/, ' ')).to_s + "(#{ex.class})")
    if on_fatal_error = @on_fatal_error
      on_fatal_error.call(ex)
    else
      close_socket
      exit(1)
    end
  end
```

By using `@on_fatal_error`, you can re-raise `ex` or do any other error handling.

How do you think about this?

**Comment by arcage** [comment]
> If you'd rather not, I'm happy to put a little more work in and divide out the functionality we need into a separate gem.

Did you mean that you want to fork and rebuild this to conform with your project?

**Comment by arcage** [comment]
Sorry, I was wrong.
I withdraw the above proposal that using `exit()`.

When sending emails concurrently, using `exit()` affects all other Fibers that successfully sending emails.

After all, `exit()` should not be used.

I will reconsider that.

**Comment by robacarp** [comment]
> Did you mean that you want to fork and rebuild this to conform with your project?

That's certainly one option but I don't think that's necessary. A fatal error handler, or some other solution is just fine. I'm offering to help with the code as needed :]

**Comment by arcage** [comment]
v0.2.5 that removed calling `exit()` and added `on_fatal_error` is released.

> I'm offering to help with the code as needed :]

That would be great.

Thank you for your cooperation.

**Comment by robacarp** [comment]
Thanks again for your help @arcage
