### ISSUE TITLE
Setting custom headers

### ISSUE THREAD

**Issue by oneiros** [arcage/crystal-email#39]
First of all: Thank you so very much for this awesome shard!

I used it to add smtp capabilities to carbon, the email library used by the lucky web framework. My adapter (https://github.com/oneiros/carbon_smtp_adapter) is super simple, but seems to work quite well thanks to your library doing all the heavy lifting :smile: 

There is only one thing missing, that carbon supports and crystal-email does not: The ability to set custom email headers.

I think this would be super useful, especially when developing issue tracker type systems, or really any system that sends emails that should be easy to filter.

I would love to see this feature added to crystal-email. Also, I would be happy to give it a go myself and prepare a PR, if that would be acceptable.

**Comment by arcage** [comment]
Thank you for your suggestion.

As you said, that feature seems to be very useful.

I have released v0.3.2 that supports custom header setting.

Do you think about it?

**Comment by oneiros** [comment]
This is absolutely fantastic! Thank you so much.
