### ISSUE TITLE
Feature Request: Timeout

### ISSUE THREAD

**Issue by iambudi** [arcage/crystal-email#41]
Hi, thank you for the great shard. 
To reduce waiting time during sending mail due to smtp server down or slow in response, what do you think if add an option for timeout?

**Comment by arcage** [comment]
Thank you for your suggestion.

It's seem to be useful.

However, I think there are too many config settings as constructor arguments of EMail::Client object.

To simplify the settings, I have been trying to split the SMTP client settings to EMail::Client::Config class.

I will add timeout setting to that new class.

But, I may take little time for that.

**Comment by iambudi** [comment]
I'm thinking if smtp_helo can be made as public method? Let's say we have a bunch of emails to be sent, rather then failed to submit when server is unreachable, can we first test once by call smpt helo before?

**Comment by arcage** [comment]
Thank you for comments.

Basically, I think the SMTP session should be established only when there are emails that have to be sent.

I made this shard so.

From my perspective, there is no difference between using `smtp_hello` independently and using it in the sequence in SMTP session.

In the case that the test fails, the error that same as if you sent e-mail as usual will occur, and you should handle it.

On the other side, even if that test is passed, there is no guarantee that the actual email sending will succeed. 

But, I don't have used this shard to send huge number of emails. So, I am not versed in probrems specific to such situation.

How do you plan to use smtp_hello as the test?

**Comment by iambudi** [comment]
> How do you plan to use smtp_hello as the test?

I'm creating a simple microservice for sending mails. I have a scheduler per minute that will ping smtp server whether it's alive by submitting ehlo/helo command and keep the status in its class instance variable.
For each incoming mail request from API, i would put on a queue and spread to several job workers when the server is in status alive.

> On the other side, even if that test is passed, there is no guarantee that the actual email sending will succeed.

I agree with you, this is just for early checking so no worker resource wasted by submitting a lot of emails while actually the server itself is down.

Separating the EHLO test in your shards seems just adding a bit complexity and people rarely will use that. So it's better to do the test in my micro service.
Your shard code is nice so that i can just 'steal' the logic and put in internal class to do just EHLO check 😉. 

Thank you.

**Comment by arcage** [comment]
> i can just 'steal' the logic and put in internal class to do just EHLO check 😉.

If my code will help you, please use it freely.

**Comment by arcage** [comment]
I have released v0.4.0 that includes few timeout related settings.

You can use `EMail::Client::Config#connect_timeout=` to set connection timeout.

See https://www.denchu.org/crystal-email/EMail/Client/Config.html

**Comment by iambudi** [comment]
Thank you so much.
