### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by iambudi** [arcage/crystal-email#42]
I can't still reproduce the issue since it's just randomly happened.
```
Unhandled exception in spawn: SSL_shutdown: No such file or directory (Errno)
  from /usr/local/Cellar/crystal/0.27.0/src/openssl.cr:115:15 in 'initialize'
  from /usr/local/Cellar/crystal/0.27.0/src/openssl.cr:100:7 in 'new'
  from /usr/local/Cellar/crystal/0.27.0/src/openssl/ssl/socket.cr:150:17 in 'unbuffered_close'
  from /usr/local/Cellar/crystal/0.27.0/src/io/buffered.cr:215:5 in 'close'
  from lib/email/src/email/client.cr:318:7 in 'close_socket'
  from /usr/local/Cellar/crystal/0.27.0/src/fiber.cr:255:3 in 'run'
  from /usr/local/Cellar/crystal/0.27.0/src/fiber.cr:75:34 in '->'
```

**Comment by arcage** [comment]
That you for reporting.

I have traced your error messages.

It seems that error occured when the SSL_shutdown function in LibSSL was called during ssl socket closing. However, I couldn't make clear why it occurred.

Please let me know If you find the trigger of this error.

**Comment by iambudi** [comment]
I can reproduce the error. 
It happen when error is not captured both in on_fatal_error or  on_failed during mail send.
My SMTP server does not allow submit from different sender (from), but i force to submit using different one, this trigger error : `Client does not have permissions to send as this sender` and trigger SSL error unbuffered_close.

At the moment, i wrap EMail.send() inside begin .. rescue to avoid the error. 
Should all error expected to be captured in on_fatal_error?

I have difficulty to differentiate exception type for each error raised. Any clue?

**Comment by arcage** [comment]
Thank you for clarifying the root of problem.

I got it.
`Client#close_socket` is called in the `ensure` block of `Client#start`. Because the `ensure` block is out of the `rescure` target, the error in `close_socket` had never rescured.

I have put `begin ... rescue ... end` on that `ensure` to call `fatal_error` when some error occur, and updated repo.

Could you try it?

**Comment by arcage** [comment]
Sorry, I closed this by mistake.

**Comment by iambudi** [comment]
Hi, it's now working as expected and the error can be captured in on_fatal_error. Thank you so much for the fix.
I can close the issue.
