### ISSUE TITLE
Attachment File Corrupted

### ISSUE THREAD

**Issue by iambudi** [arcage/crystal-email#44]
I test attaching an image file. In the debug log, it shows the file size of attachment file correctly and the mail successfully delivered.
When i open the attachment in mail client, the file seems corrupt since it shows image partially.

**Comment by arcage** [comment]
Thank you for reporting.

I verified attachment file encoding process and find that problem occur when attached file size is greater than 8KB.

I'm sorry for testing the file attachment function with only small files.

It should be fixed on the next release that will come in a few days.

**Comment by arcage** [comment]
I have released v0.4.0 that solves this Issue.

Could you check this version?

**Comment by iambudi** [comment]
Awesome, thank you for your prompt response and fix.
I retested and the image file attachment now shows perfectly.
