### ISSUE TITLE
Local email addresses

### ISSUE THREAD

**Issue by KaneRoot** [arcage/crystal-email#54]
Hello,

I tried to run the minimal example with simple local addresses, "login" and "login@localhost", and it doesn't work. The given error is:

```
Unhandled exception: "login" is invalid as a mail address. (EMail::Error::AddressError)
  from lib/email/src/email/address.cr:0:5 in 'valid_address!'
  from lib/email/src/email/address.cr:32:13 in 'initialize'
  from lib/email/src/email/address.cr:31:3 in 'new'
  from lib/email/src/email/header.cr:114:16 in 'add'
  from lib/email/src/email/message.cr:415:3 in 'from'
  from src/mail-tester.cr:6:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:86:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

I had to enter `login@localhost.localdomain` to make it work (changing my smtpd configuration along the way).

With a simple tool such as `mailx` we can just put our login: `echo hello | mailx -s subject login`.

Is there a reason not to make it work with local logins? Should I configure `EMail::Client::Config` differently?

**Comment by arcage** [comment]
Thank you for reporting.

This was caused by my misunderstanding for email address specs.

I will fix this.

**Comment by KaneRoot** [comment]
Thanks for your quick response and patch!

I do think that your code could be significantly more readable and robust using the Grok library, in order not to maintain your own regex. https://github.com/spinscale/grok.cr
That can be applied to emails and plenty of other formatted strings.

**Comment by arcage** [comment]
Thanks for the shard information.

From what I'v seen, that shards doesn't seems to check the email address format correctly.

For example, the general hostname cannot contain adjacent ".", but that shard accept it.

Of course, current my implementation is not perfect too, but I think it should be checked a bit more strictly.

**Comment by KaneRoot** [comment]
I agree. I hope someone could help Grok to have a better implementation, so everyone can just use a single implementation without being bothered ever again with the stupid complexity of the email address format.
