### ISSUE TITLE
Shard.yml doesn't indicate shared libraries needed

### ISSUE THREAD

**Issue by HCLarsen** [arcage/crystal-email#69]
I'm experiencing a number of errors while building an app in Ubuntu that uses this library. If I understand correctly, it's because certain libraries like libssl and libcrypto aren't install on this system. For future users, it would be useful to have those libraries listed in the shard.yml file.

https://github.com/crystal-lang/shards/blob/master/SPEC.md#libraries

**Comment by arcage** [comment]
Thank you for your suggestion.

I will check the behavior on Ubuntu, then consider it.

**Comment by arcage** [comment]
I have read the SPEC of **shard.yml**.

It says:
> A shard must only list libraries it directly links to, it must not include libraries that are only referenced by dependencies. 

This shard doesn't directly link any libraries, but just use TLS via standard library functions.

In this case, I think this shard should not list any libraries in the **shard.yml**.

Instead, I will state on the docs this shard may use libssl and libcrypto to handle TLS connections.

**Comment by arcage** [comment]
README updated.

Thanks.
