### ISSUE TITLE
HTML Emails

### ISSUE THREAD

**Issue by crisward** [arcage/crystal-email#7]
Any plans to add html support?

If not, any pointers on how best to do this?

Thanks.

**Comment by arcage** [comment]
Thanks for your comment.
And, sorry for late reply.

To handling HTML emails, I have to learn email message format more deeply to include the resources other than HTML itself (eg: images, stylesheets, etc...) as the part of email contents, or to handle multipart/alternative type contents correctly.

At the beginning, I will try to implement minimum HTML email handling.

**Comment by arcage** [comment]
Hi, @crisward .

Although it may be useless already, I have implemented HTML e-Mail handling functions in v0.1.6 .

**Comment by crisward** [comment]
Thanks for this. That's a big help.
