### ISSUE TITLE
Is it possible to set the name of the sender?

### ISSUE THREAD

**Issue by acoolstraw** [arcage/crystal-email#75]
Wondering if it's possible to set the sender's name in this fashion: `"John Doe" <johndoe@example.com>`

**Comment by arcage** [comment]
If the "sender" you said means From header address of an email, you can set sender(mailbox) name by using the 2nd argument of `EMail::Message#from(String, String)` method.

https://www.denchu.org/crystal-email/EMail/Message.html#set-mailbox-name-with-email-address

**Comment by acoolstraw** [comment]
Thank you for the quick response! It worked, I don't know how I missed that part of the documentation...
